les2_mains_homepage:
    path:     /
    defaults: { _controller: les2MainsBundle:Default:index }

les2_mains_nous:
    path:     /nous
    defaults: { _controller: les2MainsBundle:Our:nous }

les2_mains_add:
    path:     /add
    defaults: { _controller: les2MainsBundle:Our:add }

les2_mains_admin:
    path:     /admin
    defaults: { _controller: les2MainsBundle:Default:admin }


