les2_mains_homepage:
    path:     /
    defaults: { _controller: les2MainsBundle:Default:index }

les2_mains_nos_events:
    path:     /events
    defaults: { _controller: les2MainsBundle:Events:add }

