core_homepage:
    path:     /
    defaults: { _controller: CoreBundle:Default:index }

core_nous:
    path:     /nous
    defaults: { _controller: CoreBundle:Our:nous }

core_contact:
    path:   /contact
    defaults: { _controller: CoreBundle:Default:contact}

