core_homepage:
    path:     /
    defaults: { _controller: CoreBundle:Default:index }

core_nous:
    path:     /nous
    defaults: { _controller: CoreBundle:Our:ourForm }
    requirements:
        method: GET|POST

core_contact:
    path:   /contact
    defaults: { _controller: CoreBundle:Default:contact}

# Activity route
core_activite:
    prefix: /activite
    resource: 'routing/activite.yml'