core_homepage:
    path:     /
    defaults: { _controller: CoreBundle:Default:index }

core_nous:
    path:     /nous
    defaults: { _controller: CoreBundle:Our:nous }

core_activite:
    prefix: /activite
    resource: 'routing/activite.yml'