les2MainsBundle\Entity\Blog:
    type: entity
    table: null
    repositoryClass: les2MainsBundle\Repository\BlogRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
        dates:
            type: datetime
        contenu:
            type: text
    lifecycleCallbacks: {  }

