les2MainsBundle\Entity\Events:
    type: entity
    table: null
    repositoryClass: les2MainsBundle\Repository\EventsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        datesDebut:
            type: datetime
            column: dates_debut
        datesFin:
            type: datetime
            column: dates_fin
        prix:
            type: integer
        descriptions:
            type: text
            column: Descriptions
    lifecycleCallbacks: {  }
