les2MainsBundle\Entity\intervenants:
    type: entity
    table: null
    repositoryClass: les2MainsBundle\Repository\intervenantsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
            column: Nom
    lifecycleCallbacks: {  }
