les2MainsBundle\Entity\Nous:
    type: entity
    table: null
    repositoryClass: les2MainsBundle\Repository\NousRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
        contenu:
            type: text
    lifecycleCallbacks: {  }
