les2MainsBundle\Entity\TVA:
    type: entity
    table: null
    repositoryClass: les2MainsBundle\Repository\TVARepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        taux:
            type: integer
        nom:
            type: string
            length: 255
    lifecycleCallbacks: {  }
