CoreBundle\Entity\ActiviteType:
    type: entity
    table: null
    repositoryClass: CoreBundle\Repository\ActiviteTypeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
    lifecycleCallbacks: {  }
