
core_activite_add:
    path:     /add
    defaults: { _controller: CoreBundle:Activite:add }


core_activite_delete:
    path:     /{id}/delete
    defaults: { _controller: CoreBundle:Activite:delete}

core_activite_editValide:
    path:     /{id}/activite/edit
    defaults: { _controller: CoreBundle:Activite:valideEdit }

