CommerceBundle\Entity\Marchandise:
    type: entity
    table: null
    repositoryClass: CommerceBundle\Repository\MarchandiseRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        prix:
            type: integer
        quantite:
            type: integer

    manyToOne:
        evenements:
            targetEntity: CommerceBundle\Entity\Evenement
            inversedBy: marchandises
        products:
            targetEntity: CommerceBundle\Entity\Product
