CommerceBundle\Entity\SelectProduit:
    type: entity
    table: null
    repositoryClass: CommerceBundle\Repository\SelectProduitRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        quantiteCommande:
            type: float
        prixTotal:
            type: float
            column: PrixTotal

    manyToOne:
        user:
            targetEntity: CommerceBundle\Entity\User
            inversedBy: selectProduits
        product:
            targetEntity: CommerceBundle\Entity\Product