# Route stage
event_add:
    path: /events
    defaults: {_controller: CommerceBundle:Event:addEvent}
    methods: ['GET', 'POST']

event_delete:
    path: /event/delete/{id}
    defaults: {_controller: CommerceBundle:Event:deleteEvent}

event_edit_valid:
    path: /{id}/event/edit
    defaults: {_controller: CommerceBundle:Event:validEdit}

event_edit:
    path: /editEvent
    defaults: { _controller: CommerceBundle:Event:editEvent }


# Route gestion des produits
product:
    path: /product
    defaults: {_controller: CommerceBundle:Product:addProduct}

product_delete:
    path: /{id}/product/delete
    defaults: {_controller: CommerceBundle:Product:delete}

edit_valid_product:
    path: /{id}/product/edit
    defaults: {_controller: CommerceBundle:Product:validEditProduct}

product_edit:
    path: /editProduct
    defaults: { _controller: CommerceBundle:Product:editProduct}


# Route booking user
list_evenementAction:
    path: /evenement
    defaults: {_controller: CommerceBundle:BookingUser:listEvenenement}

booking:
    path: /{id}/booking
    defaults: {_controller: CommerceBundle:BookingUser:booking}
    requirements:
        id: '\d+'

recap_booking:
    path: /{id}/recap/booking
    defaults: {_controller: CommerceBundle:BookingUser:RecapBooking}

valid_booking:
    path: /{id}/valid
    defaults: {_controller: CommerceBundle:BookingUser:validBooking}



# Route booking admin
add_booking:
    path: /admin/booking
    defaults: {_controller: CommerceBundle:BookingAdmin:addBooking}

add_marchandises:
    path: /admin/booking/marchandise
    defaults: {_controller: CommerceBundle:BookingAdmin:addMarchandise}

delete_evenement:
    path: /{id}/delete/evenement
    defaults: {_controller: CommerceBundle:BookingAdmin:deleteEvenement}
    requirements:
            id: '\d+'

delete_marchandises:
    path: /admin/delete/marchandise
    defaults: {_controller: CommerceBundle:BookingAdmin:deleteMarchandise}