
commerce_events:
    path:     /events
    defaults: { _controller: CommerceBundle:Event:Event }


activite:
    path:     /activite
    defaults: {  _controller: CommerceBundle:Activite:Activite }

produit:
    path:     /produit
    defaults: {  _controller: CommerceBundle:Produit:Produit }


