event_add:
    path: /events
    defaults: {_controller: CommerceBundle:Event:addEvent}
    methods: ['GET', 'POST']

event_delete:
    path: /event/delete/{id}
    defaults: {_controller: CommerceBundle:Event:deleteEvent}

event_edit_valid:
    path: /{id}/event/edit
    defaults: {_controller: CommerceBundle:Event:validEdit}

event_edit:
    path: /editEvent
    defaults: { _controller: CommerceBundle:Event:editEvent }



product:
    path: /product
    defaults: {_controller: CommerceBundle:Product:addProduct}

product_delete:
    path: /{id}/product/delete
    defaults: {_controller: CommerceBundle:Product:delete}

edit_valid_product:
    path: /{id}/product/edit
    defaults: {_controller: CommerceBundle:Product:validEditProduct}

product_edit:
    path: /editProduct
    defaults: { _controller: CommerceBundle:Product:editProduct}



list_evenementAction:
    path: /evenement
    defaults: {_controller: CommerceBundle:Booking:listEvenenement}

delete_evenement:
    path: /{id}/delete/evenement
    defaults: {_controller: CommerceBundle:Booking:deleteEvenement}
    requirements:
            id: '\d+'


booking:
    path: /{id}/booking
    defaults: {_controller: CommerceBundle:Booking:booking}
    requirements:
        id: '\d+'

valid_booking:
    path: /{id}/valid
    defaults: {_controller: CommerceBundle:Booking:validBooking}

add_booking:
    path: /admin/booking
    defaults: {_controller: CommerceBundle:Booking:addBooking}

recap_booking:
    path: /{id}/recap/booking
    defaults: {_controller: CommerceBundle:Booking:RecapBooking}


