event_add:
    path: /events
    defaults: {_controller: CommerceBundle:Event:addEvent}
    methods: ['GET', 'POST']

event_delete:
    path: /event/delete/{id}
    defaults: {_controller: CommerceBundle:Event:deleteEvent}

event_edit_valid:
    path: /{id}/event/edit
    defaults: {_controller: CommerceBundle:Event:validEdit}